### ISSUE TITLE
Attribute error when executing check

### ISSUE THREAD

**Issue by carlesonielfa** [emlyn/sonic-pi-tool#6]
There is an Attribute Error when executing the tool:

```
File "d:/OneDrive - Universitat de Barcelona/OP-Pi/software/sonic-pi-tool.py", line 100, in server_port_in_use
    sock.bind(('127.0.0.1', self.port))
AttributeError: 'Server' object has no attribute 'port'
```

Changing the line to 
`sock.bind(('127.0.0.1', self.osc_port))`
fixes the error but I don't know if in this line you meant to use osc_port or cmd_port

**Comment by emlyn** [comment]
Thanks for reporting this, I've pushed a fix but there are more changes needed to make it compatible with the latest releases (which I'll hopefully get around to sorting out soon)
